StarWars/StarWars/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view

import mainapp.urls as mainapp
from mainapp.endpoints.api_recruit import RecruitViewSet, PlanetViewSet, SithViewSet

schema_view = get_schema_view(title='Pastebin API')

router = DefaultRouter()
router.register('recruits', RecruitViewSet)
router.register('planets', PlanetViewSet)
router.register('siths', SithViewSet)

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include(mainapp)),
                  path('api/', include(router.urls)),
                  path('schema/', schema_view),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

StarWars/mainapp/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from django.conf.urls.static import static
from mainapp.views import mainapp_index, RecruitGenericCreate, \
    TestDetail, RecruitsList, SithList, \
    RecruitTestResults, recruit_approve, save_test, \
    ReportTotalSithList, ReportSithList

app_name = 'main'

urlpatterns = [
    path('', mainapp_index, name='start_page'),
    path('recruits/create/', RecruitGenericCreate.as_view(), name='recruits_create'),
    re_path('^recruits/test-pass/(?P<slug>\w+)$', TestDetail.as_view(), name='test-pass'),
    re_path('^siths/recruits-list/(?P<slug>\w+)$', RecruitsList.as_view(), name='recruits_list'),
    re_path('^siths/recruit-test-results/(?P<slug>\w+)$', RecruitTestResults.as_view(), name='recruit_test_results'),
    path('siths/', SithList.as_view(), name='sith_list'),
    path('siths/recruit-approve', recruit_approve, name='recruit_approve'),
    path('recruits/save-test/<int:pk>/', save_test, name='save_test'),
    path('reports/total-sith-list', ReportTotalSithList.as_view(), name='report_total_sith_list'),
    path('reports/sith-list', ReportSithList.as_view(), name='report_sith_list'),
]

StarWars/mainapp/models.py
from django.db import models


class Planet(models.Model):
    name = models.CharField(verbose_name='Наименование', max_length=60, unique=True,
                            error_messages={'required': 'Укажите наименование планеты'})
    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Recruit(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=60,
                            error_messages={'required': 'Заполните имя!'})
    planet = models.ForeignKey(Planet, on_delete=models.CASCADE, verbose_name='Планета обитания')
    age = models.PositiveIntegerField(verbose_name='Возраст', blank=True)
    email = models.EmailField()
    created = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    def __str__(self):
        return "имя: {}, планета: {}, возраст: {}, email: {}".format(self.name, self.planet, self.age, self.email)

    class Meta:
        ordering = ['name']


class Sith(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=60, unique=True,
                            error_messages={'required': 'Заполните имя!'})
    planet = models.ForeignKey(Planet, on_delete=models.CASCADE, verbose_name='Планета')
    created = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    def __str__(self):
        return "имя: {}, планета: {}".format(self.name, self.planet)

    class Meta:
        ordering = ['name']


class Question(models.Model):
    text = models.TextField(verbose_name='Вопрос',
                            error_messages={'required': 'Заполните текст вопроса!'})


class Test(models.Model):
    orden = models.ForeignKey(Planet, on_delete=models.CASCADE, verbose_name='Орден')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name='Вопрос')


class TestResult(models.Model):
    recruit = models.ForeignKey(Recruit, on_delete=models.CASCADE, verbose_name='Рекрут')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name='Вопрос')
    answer = models.TextField(verbose_name='Ответ')
    created = models.DateTimeField(auto_now_add=True, verbose_name="Дата ответа")


class Mentoring(models.Model):
    recruit = models.ForeignKey(Recruit, on_delete=models.CASCADE, verbose_name='Рекрут')
    sith = models.ForeignKey(Sith, on_delete=models.CASCADE, verbose_name='Ситх')
    created = models.DateTimeField(auto_now_add=True, verbose_name="Дата зачисления")
    is_active = models.BooleanField(verbose_name='Запись активна', default=True)
    is_refuse = models.BooleanField(verbose_name='Отказ', default=False)

    class Meta:
        unique_together = ('recruit', 'sith', 'is_active', )

StarWars/mainapp/forms.py
from django import forms

from mainapp.models import Recruit, Test, Sith


class RecruitModelForm(forms.ModelForm):
    class Meta:
        model = Recruit
        fields = ['name', 'planet', 'age', 'email']


class TestModelForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = ['question']


class SithForm(forms.ModelForm):
    class Meta:
        model = Sith
        fields = ('name',)
        widgets = {'name': forms.Select()}
        labels = {'name': 'Ваше имя: '}

StarWars/mainapp/views.py
import ast

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, render_to_response
from django.contrib import messages
from django.views.generic import (
    TemplateView,
    FormView, CreateView, UpdateView,
    DeleteView, ListView, DetailView,
)
from django.db import models
from django.db.models import Count
from django.urls import reverse, reverse_lazy
from django.conf import settings
from django.shortcuts import redirect
from django.core.mail import send_mail

from mainapp.models import Recruit, Test, Sith, TestResult, Mentoring, Question
from mainapp.forms import RecruitModelForm, TestModelForm, SithForm


def mainapp_index(request):
    return render(request, 'mainapp/index.html', {'message': ''})


# For recruits
# class CategoryGenericCreate(SuperUserMixin, CreateView):
class RecruitGenericCreate(CreateView):
    model = Recruit
    form_class = RecruitModelForm
    template_name = 'create.html'

    # success_url = reverse_lazy('main:start_page')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Вступить в ряды'
        context['OK_text'] = 'Далее'
        return context

    def get_success_url(self):
        return reverse('main:test-pass', kwargs={'slug': self.object.id})


class TestDetail(DetailView):
    model = Recruit
    form_class = TestModelForm
    template_name = 'mainapp/test.html'
    success_url = reverse_lazy('main:start_page')
    slug_field = 'id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        recruit = Recruit.objects.get(id=self.kwargs['slug'])
        test = Test.objects.filter(orden=recruit.planet)
        context['test'] = test
        context['recruit'] = recruit
        return context


def save_test(request, pk):
    data = list(ast.literal_eval(request.POST["data"]))
    recruit = Recruit.objects.get(id=int(pk))
    for row in data:
        question = Question.objects.get(id=int(row.get('question')))
        TestResult(recruit=recruit, question=question, answer=row.get('answer')).save()
    success_url = redirect('main:start_page')
    return success_url


# For sith
class SithList(ListView):
    template_name = 'mainapp/sith.html'
    queryset = Sith.objects.order_by('name')
    context_object_name = 'sith'


class RecruitsList(ListView):
    template_name = 'mainapp/recruits_list.html'

    # queryset = Sith.objects.order_by('name')

    def get_queryset(self):
        self.request.session["sith"] = self.kwargs['slug']
        sith = Sith.objects.get(name=self.kwargs['slug'])
        mentor_inactive = Mentoring.objects.filter(is_active=False).exclude(is_refuse=False)
        mentor_active = Mentoring.objects.filter(is_active=True)
        mentor_all = mentor_active | mentor_inactive
        recruit_has_mentor = [i.recruit.id for i in mentor_all]
        qs = TestResult.objects.filter(recruit__planet=sith.planet).distinct('recruit'). \
            exclude(recruit__in=recruit_has_mentor)
        return qs

    context_object_name = 'recruits'


class RecruitTestResults(ListView):
    template_name = 'mainapp/test_results.html'

    def get_queryset(self):
        qs = TestResult.objects.filter(recruit=self.kwargs['slug'])
        return qs

    context_object_name = 'results'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['sith'] = self.request.session["sith"]
        return data


def recruit_approve(request):
    # if request.method == 'POST':
    recruit_id = request.POST['recruit']
    sith_name = request.POST['sith']
    max_students = 3
    # Проверка на кол-во рук тени
    stud_qs = Mentoring.objects.filter(sith__name=sith_name).filter(is_active=True)
    count_students = stud_qs.count()

    if count_students >= max_students:
        students = [st.recruit.name for st in stud_qs]
        students = ', '.join(students)
        message = f'Зачисление невозможно! Максимальное количество Рук тени: {max_students}. Ваши ученики: {students}'
        return render(request, 'mainapp/index.html', {'message': message})

    # Зачислить
    recruit = Recruit.objects.get(id=int(recruit_id))
    sith = Sith.objects.get(name=sith_name)
    new_recruit = Mentoring(recruit=recruit, sith=sith)
    new_recruit.save()
    success_url = redirect('main:recruits_list', slug=sith_name)

    # Отправка письма
    subject = 'Информация о зачислении'
    body = f'{recruit.name}, поздравляем! Вы зачислены в Орден. Ваш наставник: {sith_name}'
    mail_from = settings.EMAIL_HOST_USER
    mail_to = [recruit.email, ]
    send_mail(
        subject,
        body,
        mail_from,
        mail_to,
        fail_silently=False,
    )
    return success_url


# Reports
# Список ситхов с количеством Рук тени
class ReportTotalSithList(ListView):
    template_name = 'mainapp/report_total_sith_list.html'

    def get_queryset(self):
        qs = Mentoring.objects.values('sith__name').annotate(recr_count=Count('recruit'))
        return qs

    context_object_name = 'results'


# Список ситхов, у которых более 1-й руки тени
class ReportSithList(ListView):
    template_name = 'mainapp/report_sith_list.html'

    def get_queryset(self):
        # qs = Mentoring.objects.values('sith__name').annotate(recr_count=Count('recruit'))
        qs = Mentoring.objects.values('sith__name').annotate(recr_count=Count('recruit')).filter(recr_count__gt=1)
        return qs

    context_object_name = 'results'

StarWars/mainapp/templates/mainapp/index.html
{% extends 'master.html' %}

{% load static %}

{% block page_title %} Служба рекрутинга  {% endblock %}
{% block page_styles %}
<link rel="stylesheet" href="{% static 'StarWars/style.css' %}">

{% endblock %}

{% block script %}
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
{% if message %}
<script>
        alert("{{ message }}");

</script>
{% endif %}

{% endblock %}

{% block page_content %}

{{ block.super }}
<div class="main-choice">

    <form action="{% url 'main:recruits_create' %}">
        <input type="submit" value="Для Рекрутов" id="subm1"/>
    </form>

    <form action="{% url 'main:sith_list' %}">
        <input type="submit" value="Для Ситхов" id="subm2"/>
    </form>

</div>

{% endblock %}

StarWars/mainapp/templates/mainapp/recruits_list.html
{% extends 'master.html' %}

{% load static %}

{% block page_title %} Список рекрутов {% endblock %}
{% block page_styles %}
    <link rel="stylesheet" href="{% static 'StarWars/style.css' %}">

{% endblock %}

{% block script %}
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">

{% endblock %}

{% block page_content %}

    {{ block.super }}
<h2><b>Кандидаты к зачислению</b></h2>
<ul>
    {% for r in recruits %}

        <a href="{% url 'main:recruit_test_results' r.recruit.id %}">
            <li>  {{ r.recruit.name }} </li>
        </a>
    {% empty %}
    <div>
        Рекруты к зачислению отсуствуют :(
    </div>

    {% endfor %}
  </ul>

{% endblock %}

StarWars/mainapp/templates/mainapp/report_sith_list.html
{% extends 'master.html' %}

{% load static %}

{% block page_title %} Статистика. Ситхи с несколькими учениками {% endblock %}
{% block page_styles %}
<link rel="stylesheet" href="{% static 'StarWars/style.css' %}">

{% endblock %}

{% block script %}
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">

{% endblock %}

{% block page_content %}

{{ block.super }}

<div class="report-sith-list">
    <h2><b>Список ситхов с несколькими учениками</b></h2>
    {% for r in results %}
    <li>
        {{r.sith__name}}
    </li>
    {% endfor %}
</div>

{% endblock %}

StarWars/mainapp/templates/mainapp/report_total_sith_list.html
{% extends 'master.html' %}

{% load static %}

{% block page_title %} Статистика. Количество Рук тени {% endblock %}
{% block page_styles %}
<link rel="stylesheet" href="{% static 'StarWars/style.css' %}">

{% endblock %}

{% block script %}
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">

{% endblock %}

{% block page_content %}

{{ block.super }}

<table border="1">
    <caption>Статистика по ситхам в разрезе Рук тени</caption>
    <tr>
        <th>Ситх</th>
        <th>Количество Рук тени</th>
    </tr>
    {% for r in results %}
    <tr>
        <td>
            {{r.sith__name}}
        </td>
        <td>
            {{r.recr_count}}
        </td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

StarWars/mainapp/templates/mainapp/sith.html
{% extends 'master.html' %}

{% load static %}

{% block page_title %} Добро пожаловать!  {% endblock %}
{% block page_styles %}
<link rel="stylesheet" href="{% static 'StarWars/style.css' %}">

{% endblock %}

{% block script %}
<script>
    function ShowList() {
        document.location=document.getElementById('sith_list').options[document.getElementById('sith_list').selectedIndex].value;
    }

</script>

{% endblock %}

{% block page_content %}

{{ block.super }}
<!--<form method="POST" enctype="multipart/form-data">-->
<p class="your-name"><b>Ваше имя:</b></p>
<form>
    {% csrf_token %}
    <select id="sith_list">
        {% for s in sith %}
        <option value="{% url 'main:recruits_list' s.name %}">
            {{ s.name }}
        </option>
        {% endfor %}
    </select>
    <div class="OK_button">
        <input type="button" value="Выбрать" onClick="ShowList();">
    </div>

</form>
{% endblock %}

StarWars/mainapp/templates/mainapp/test.html
{% extends 'master.html' %}

{% load static %}

{% block page_title %} Тестовое испытание
{% endblock %}
{% block page_styles %}
<link rel="stylesheet" href="{% static 'StarWars/style.css' %}">
{% endblock %}

{% block script %}
<script>
        function fmSubmit() {
        let list = [];
    let row_data, class_el, value_el, id_el;

    table = document.querySelector('#test');
    for (let row of table.rows) {
    if (row.getAttribute('class') != "table-header") {
<!--        row_data = new Map();-->
            row_data = {};
        for (let cell of row.cells) {
            id_el = cell.getAttribute('id');
            class_el = cell.getAttribute('class');
            if (id_el) {
                row_data[class_el]=id_el;
            }
            else {
                let inputs = cell.getElementsByTagName('input');

                for (let input of inputs) {
                    if (input.checked) {
<!--                        row_data.set(class_el, input.value);-->
                            row_data[class_el]=input.value;
                    }
                }
            }
        }

        list.push(row_data);
    }
    }

        alert("Готово! В случае положительного ответа Вам придет приглашение по email");
        document.getElementById("data").value = JSON.stringify(list);

    }

</script>
{% endblock %}

{% block page_content %}
{{ block.super }}
<div>
    <main class="main">
        <form action="{% url 'main:save_test' recruit.id %}" method="post" onsubmit="fmSubmit()">
            {% csrf_token %}
            <table id="test" border="1">
                <caption>Вступительный тест</caption>
                 <col width="250">
                 <col width="150">
                <tr class="table-header">
                    <th>Вопрос</th>
                    <th>Ответ</th>
                </tr>
                {% for t in test %}
                <tr>
                    <td id="{{ t.question.id }}" class="question">
                        {{t.question.text}}
                    </td>
                    <td class="answer">
                        <label>
                            <input type="radio" name="{{ t.question.id }}" value="Да" required>Да
                        </label>
                        <label>
                            <input type="radio" name="{{ t.question.id }}" value="Нет">Нет
                        </label>
                    </td>
                </tr>
                {% endfor %}
            </table>

            <input type="hidden" id="data" name="data">
            <input type="submit" value="Отправить" class="send-button">
        </form>

    </main>

</div>
{% endblock %}

StarWars/mainapp/templates/mainapp/test_results.html
{% extends 'master.html' %}

{% load static %}

{% block page_title %} Результаты теста {% endblock %}
{% block page_styles %}
<link rel="stylesheet" href="{% static 'StarWars/style.css' %}">

{% endblock %}

{% block script %}
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">

{% endblock %}

{% block page_content %}

{{ block.super }}

<table border="1">
    <caption>Тест рекрута {{results.0.recruit.name}}</caption>
    <tr>
        <th>Вопрос</th>
        <th>Ответ</th>
    </tr>
    {% for r in results %}
    <tr>
        <td>
            {{r.question.text}}
        </td>
        <td>
            {{r.answer}}
        </td>
    </tr>
    {% endfor %}
</table>
<form action="{% url 'main:recruit_approve' %}" method="post">
    {% csrf_token %}
    <input type="hidden" id="recruit" name="recruit" value={{results.0.recruit.id}}>
    <input type="hidden" id="sith" name="sith" value={{sith}}>
    <input type="submit" value="Зачислить" class="send-button">
</form>

{% endblock %}