StarWars/StarWars/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view

import mainapp.urls as mainapp
from mainapp.endpoints.api_recruit import RecruitViewSet, PlanetViewSet, SithViewSet

schema_view = get_schema_view(title='Pastebin API')

router = DefaultRouter()
router.register('recruits', RecruitViewSet)
router.register('planets', PlanetViewSet)
router.register('siths', SithViewSet)

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include(mainapp)),
                  path('api/', include(router.urls)),
                  path('schema/', schema_view),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

StarWars/mainapp/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from django.conf.urls.static import static
from mainapp.views import mainapp_index, RecruitGenericCreate, \
    TestDetail, RecruitsList, SithList, \
    RecruitTestResults, recruit_approve, save_test, \
    ReportTotalSithList, ReportSithList

app_name = 'main'

urlpatterns = [
    path('', mainapp_index, name='start_page'),
    path('recruits/create/', RecruitGenericCreate.as_view(), name='recruits_create'),
    re_path('^recruits/test-pass/(?P<slug>\w+)$', TestDetail.as_view(), name='test-pass'),
    re_path('^siths/recruits-list/(?P<slug>\w+)$', RecruitsList.as_view(), name='recruits_list'),
    re_path('^siths/recruit-test-results/(?P<slug>\w+)$', RecruitTestResults.as_view(), name='recruit_test_results'),
    path('siths/', SithList.as_view(), name='sith_list'),
    path('siths/recruit-approve', recruit_approve, name='recruit_approve'),
    path('recruits/save-test/<int:pk>/', save_test, name='save_test'),
    path('reports/total-sith-list', ReportTotalSithList.as_view(), name='report_total_sith_list'),
    path('reports/sith-list', ReportSithList.as_view(), name='report_sith_list'),
]

StarWars/StarWars/templates/includes/form.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% for err in forms.not_field_errors %}
        <div class="alert alert-danger" role="alert">
            <span>{{ err }}</span>
        </div>
    {% endfor %}

    <div class="form-group">
        {% for field in form %}

            <div class="form-field">
                <label for="{{ field.name }}">
                    {{ field.label }}:
                </label>
                {{ field }}
            </div>
        {% endfor %}

    <div class="OK_button">
        <input type="submit" value="{{ OK_text }}">
    </div>
    </div>
    {% for field in form %}
        {% if field.errors|length > 0 %}
            {% for err in field.errors %}
                <small class="form-text">{{ err }}</small>
            {% endfor %}
        {% endif %}
    {% endfor %}
</form>

StarWars/StarWars/templates/includes/inc_menu.html
{% load static %}

<nav>
    <ul class="menu">
        <li><a href="{% url 'main:start_page' %}">Главная</a></li>
        <li>
            <div class="btn-group">
                <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                    Статистика
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'main:report_total_sith_list' %}">Статистика по ситхам в
                        разрезе Рук тени</a>
                    <a class="dropdown-item" href="{% url 'main:report_sith_list' %}">Список ситхов с несколькими
                        учениками</a>
                </div>
            </div>
        </li>
        <li>
            <div class="btn-group">
                <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                    Rest-API
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="/api/planets">Планеты</a>
                    <a class="dropdown-item" href="/api/siths">Ситхи</a>
                    <a class="dropdown-item" href="/api/recruits">Рекруты</a>
                </div>
            </div>
        </li>
        <li><a href="/admin/">Настройка</a></li>
    </ul>
</nav>